# Generated by Django 3.0.6 on 2020-06-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=150)),
                ('idade', models.CharField(default='', max_length=3)),
                ('telefone', models.CharField(default='', max_length=15)),
                ('ativo', models.BooleanField(default=False)),
            ],
        ),
    ]
